### ISSUE TITLE
How to add upload feature to existing gae-init app?

### ISSUE THREAD

**Issue by jaxon** [gae-init/gae-init-upload#18]
I'm already running gae-init in production, how do I add the upload feature to it?

Even a diff between gae-init and gae-init-upload would suffice.

**Comment by lipis** [comment]
Just do the following

```
git pull https://github.com/gae-init/gae-init-upload.git master
```

or simply add the remote for future pulls

```
git remote add upload https://github.com/gae-init/gae-init-upload.git
```

and then 
```
git remote upload master
```

**Comment by lipis** [comment]
Also I would recommend doing the above pull request in a new branch.. to avoid unnecessary unwanted things :)

**Comment by jaxon** [comment]
Wow, that was painless! Plus, updates from the core gae-init. Thanks for the tip.

**Comment by lipis** [comment]
same for the other two flavors.. except maybe babel that will have more conflicts in would guess if you have changes..
