### ISSUE TITLE
Ability to Share Uploaded Resources with other Users

### ISSUE THREAD

**Issue by jaxon** [gae-init/gae-init-upload#19]
Uploaded resources (files) are currently only visible to the user who uploaded them. How can I turn this restriction off? 

The @auth.admin_required is enough for my current requirements.

**Comment by lipis** [comment]
If you want to show all the resources that are uploaded by any user, then instead this line, https://github.com/gae-init/gae-init-upload/blob/master/main/control/resource.py#L43

you can have something like this:

```python
resource_dbs, resource_cursor = model.Resource.get_dbs()
```

and remove the `@auth.login_required`

**Comment by lipis** [comment]
Is this solved?
